### ISSUE TITLE
yaks-sinatra outdated in rubygems

### ISSUE THREAD

**Issue by mpedrera** [plexus/yaks#107]
When installing `yaks-sinatra '0.10.0'` through rubygems, the version you get is [this one](https://github.com/plexus/yaks/blob/b276d5f2a56c8da3ff82f05c9df0e527725c2ca6/yaks-sinatra/lib/yaks-sinatra.rb), which still uses `Sinatra::Yaks` syntax, while the one in GitHub (and docs) uses `Yaks::Sinatra` syntax.

Therefore, if you follow current docs it doesn't work as intended. Both versions are labeled as `0.10.0`

**Comment by plexus** [comment]
This has been addressed in v0.11.0.
