### ISSUE TITLE
v0.11.0 is out

### ISSUE THREAD

**Issue by plexus** [plexus/yaks#109]
Just a quick heads up that a new version is out on Rubygems. Thanks @groyoh @janko-m @fidothe for making this one possible. It's not a massive release but there are a couple important things in there.

From the changelog:

* Updated JSON-API to match 1.0 format. ([Yohan Robert](https://github.com/groyoh) and [Janko Marohnić](https://github.com/janko-m))
* Added Yaks::Behaviour::OptionalIncludes, to support JSON-API style
  optional associations ([Janko Marohnić](https://github.com/janko-m))
* Renamed Sinatra::Yaks to Yaks::Sinatra ([Matt Patterson](https://github.com/fidothe))
* Correctly handle 'charset' in Yaks::Sinatra ([Matt Patterson](https://github.com/fidothe))
* Fix rendering of checkboxes in yaks-html
* Add integration for testing through RSpec/Capybara/Rack::Test

I'll be leaving on a month long cycling trip next week, without a laptop :D So I felt it was important to have this release out before I leave. 

Have a nice summer! (for those in the northern hemisphere at least)

![adventure_time_swing](https://cloud.githubusercontent.com/assets/32212/8594869/7f555f56-2645-11e5-93c2-3a77abda8af2.gif)

**Comment by groyoh** [comment]
:tada: Enjoy your trip! :wink:
