### ISSUE TITLE
Update or inline anima?

### ISSUE THREAD

**Issue by backus** [plexus/yaks#123]
I'm really interested in using yaks but the project I want to use it on uses anima 0.3. [The changes](https://github.com/mbj/anima/compare/v0.2.0...v0.3.0) are very straightforward but 0.3 also is limited to ruby 2.1. I'm happy to do the work to update this project and `Attribs` and I imagine you would prefer one of two options:

1. Simply update to Anima 0.3 and push a new release of yaks that only supports 2.1 and up. Ruby 1.9 and 2.0 are EOL so I think this is totally reasonable but I realize there is a small chance that you might still want to support these older rubies. 

2. Inline Anima 0.2 or 0.3 into either `yaks` or `attribs` to skirt the ruby dependency issues.

Would you be open to a PR making these changes?

**Comment by plexus** [comment]
Hi John, 

Yes, please! Dropping compatibility is fine I think in this case, I rather do that than forcing people to older versions of gems. So, pull request very welcome! 

Thanks, 
Arne
