### ISSUE TITLE
Make yaks work with resources that are coercible to an array and contain hashes

### ISSUE THREAD

**Issue by solnic** [plexus/yaks#47]
Basically making this work:

``` ruby
yaks = Yaks.new do
  default_format :hal
  rel_template 'http://api.example.com/rels/{rel}'
  format_options(:hal, plural_links: [:copyright])
  derive_mapper_from_object do |model|
    HashMapper
  end
end

class HashMapper < Yaks::Mapper
  def load_attribute(name)
    object[name]
  end

  def attributes
    object.keys
  end
end

class Collection
  def initialize(data)
    @data = data
  end

  def to_ary
    @data
  end
end

yaks.call(Collection.new([{ name: 'Jane' }])) # crashes
```

**Comment by plexus** [comment]
Are you trying to serialize instances of class `Loaded` ?

**Comment by solnic** [comment]
Oh, I think I understand now - it tries to detect the mapper. Result set is wrapped with a `ROM::Relation::Loaded` so I guess that's what's happening.

Does Yaks require a mapper and expect "objects" (as in, not hashes)? With ROM you can simply pass an array of hashes, no need for "object mapping", a simple attribute reading using `[]` would suffice.

**Comment by plexus** [comment]
Mappers are very central to Yaks. You can feed it hashes if you like, but you'll still have to specify which attributes, links, associations, forms, you want to generate.

If you just want to generically map the attributes in a hash (or something that responds to `[]`) you can do something like this

```
class HashMapper < Yaks::Mapper
  def load_attribute(name)
    object[name]
  end

  def attributes
    object.keys
  end
end

yaks.call(data, mapper: HashMapper)
```

But you might want to go straight to creating `Yaks::Resource` objects. The mapper layer is a DSL to create factories that take a specific type of input and create a `Yaks::Resource`. You can opt out of that DSL and generate a Resource directly, then serialize that.

```
yaks = Yaks.new do
  skip :map 
end

yaks.call(Yaks::Resource.new(attributes: your_hash))
```

(all code above untested :) )

**Comment by solnic** [comment]
Thanks for clarification, I couldn't get it working with a hash mapper though, but here's what works (edge ROM here):

``` ruby
require 'rom'
require 'yaks'
require 'ostruct'

ROM.setup(:memory)

class Users < ROM::Relation[:memory]
  def by_name(name)
    restrict(name: name)
  end
end

rom = ROM.finalize.env

rom.relations.users << { name: 'Jane' }
rom.relations.users << { name: 'Joe' }

yaks = Yaks.new do
  default_format :hal
  rel_template 'http://api.example.com/rels/{rel}'
  format_options(:hal, plural_links: [:copyright])
end

class UserMapper < Yaks::Mapper
  link :self, '/api/users/{name}'
  attributes :name
end

User = Class.new(OpenStruct)

users = rom.relation(:users)

puts (users >> proc { |r| r.map(&User.method(:new)) } >> yaks).call
```

and the output:

``` json
{
  "_embedded": {
    "http://api.example.com/rels/users": [
      {
        "name": "Jane",
        "_links": {
          "self": {
            "href": "/api/users/Jane"
          }
        }
      },
      {
        "name": "Joe",
        "_links": {
          "self": {
            "href": "/api/users/Joe"
          }
        }
      }
    ]
  }
}
```

**Comment by plexus** [comment]
```
 bundle exec ruby 00246.rb
/home/arne/github/rom/lib/rom/support/registry.rb:26:in `block in []': :users doesn't exist in ROM::Registry registry (ROM::Registry::ElementNotFoundError)
        from /home/arne/github/rom/lib/rom/support/registry.rb:26:in `fetch'
        from /home/arne/github/rom/lib/rom/support/registry.rb:26:in `[]'
        from /home/arne/github/rom/lib/rom/env.rb:72:in `relation'
        from 00246.rb:31:in `<main>'
```

**Comment by plexus** [comment]
That's on this line

``` ruby
users = rom.relation(:users)
```

**Comment by solnic** [comment]
@plexus right, it's in a branch (not even on master yet), I'll wrap this up and merge to master and give you an updated executable example to show the errors I was getting

**Comment by plexus** [comment]
ok, cool! overriding `load_attribute` to work with hashes should definitely work, I'll try to get you a working example

**Comment by solnic** [comment]
OK it's me again, so, here's what I've been trying:

``` ruby
require 'rom'
require 'yaks'
require 'ostruct'

ROM.setup(:memory)

class Users < ROM::Relation[:memory]
  def by_name(name)
    restrict(name: name)
  end
end

rom = ROM.finalize.env

rom.relations.users << { name: 'Jane' }
rom.relations.users << { name: 'Joe' }

yaks = Yaks.new do
  default_format :hal
  rel_template 'http://api.example.com/rels/{rel}'
  format_options(:hal, plural_links: [:copyright])
end

class HashMapper < Yaks::Mapper
  def load_attribute(name)
    object[name]
  end

  def attributes
    object.keys
  end
end

users = rom.relation(:users).by_name

puts (users >> yaks)['Jane']
```

and here's the output:

```
/Users/solnic/.gem/ruby/2.1.5/gems/yaks-0.8.1/lib/yaks/default_policy.rb:40:in `const_get': uninitialized constant LoadedMapper (NameError)
```

In this example yaks receives an instance of `ROM::Relation::Loaded` that's why it gets confused, it would be absolutely lovely if it tried to coerce to an array using `to_ary`, this way we could pass data from rom to yaks w/o the need to do anything special.

What do you think? :)

**Comment by plexus** [comment]
Not sure if that would work, if I replace your last line with

```
p users.to_ary
```

I get

```
/home/arne/github/rom/lib/rom/support/options.rb:55
```

What should work *if your collection responds to `map`* is this

```
puts yaks.call(users, item_mapper: HashMapper, mapper: Yaks::CollectionMapper)
```

Or another approach

```
yaks = Yaks.new do
  default_format :hal
  rel_template 'http://api.example.com/rels/{rel}'
  format_options(:hal, plural_links: [:copyright])

  derive_mapper_from_object do |model|
    return CoercingCollectionMapper if ROM::Relation::Loaded === model
    super(model)
  end
end

class BaseMapper < Yaks::Mapper
  # our models are accessed like hashes
  def load_attribute(name)
    object[name]
  end
end

# You still want to have these for each type to whitelist attributes,
# define links, associations, ...
class UserMapper < BaseMapper
  attributes :name
end

# For collections that don't respond to `map`, but do respond to
# `to_ary`
class CoercingCollectionMapper < Yaks::CollectionMapper
  def collection
    super.to_ary
  end
end

users = rom.relation(:users).by_name

puts (users >> yaks)['Jane']
```

although that gives me

```
00246.rb:41:in `collection': undefined method `to_ary' for #<ROM::Relation::Loaded:0x007f9c70012110> (NoMethodError)
```

What do you think? I'm happy to discuss changes, but either you're gonna have to better understand first how Yaks is intended to be used, or better explain to me how you would like to use it :)

It seems you are trying to work with unadorned data (hashes and arrays) instead of "model objects". Do you want to use mappers to declare how each type of data gets rendered, or do you just want a generic representation of the attributes?

**Comment by plexus** [comment]
I'm also quite confused about what this line does

```
puts (users >> yaks)['Jane']
```

mind to desugar that a bit? ;)

**Comment by solnic** [comment]
@plexus it finds all users with name == 'Jane' and tries to call yaks with the loaded relation. `>>` is a lower-level interface that we have to send relations through mapping objects. I was hoping it would just work with yaks but because the type of loaded relation is not an array it crashes. I'm actually surprised loaded relation doesn't respond to `to_ary`. I'm gonna fix that.

I'm pretty sure this would go in-line with how yaks is supposed to be used, it's the to-array coercion we're missing here. If it works when you pass an array, then it could also work with something that's coercible to an array.

This stuff is really exciting for me as yaks is a perfect fit for ROM. Even though I could add a small integration layer where you can register rom mappers that would use yaks mappers under-the-hood I just feel like that's not really needed and would become additional complexity, we're just passing data through mappers here after all and ROM's interface supports that.

I'm gonna dig into it more :) Thanks for help!

**Comment by plexus** [comment]
The stuff inside the relation/array, what type are those? I'm guessing since you want to bypass ROM mappers that they are some kind of generic "tuple"? Do they have knowledge of their own "type", e.g. the name of the relation? In that case I would change the Yaks policy to derive the mapper based on that. That way you could still use the declarative Yaks::Mapper DSL to specify per relation how to represent a tuple as a resource, without having to instantiate a "model" (e.g. a Virtus instance).

This is a pretty cool use case, I'm really curious to see the result :)

If you want we can schedule a walkthrough of the Yaks code. I've done it for several of my colleagues and it seems to be very enlightening. Some of the code is quite abstract, but the basic structure and mechanism is pretty simple to grasp.

**Comment by solnic** [comment]
@plexus typically relation yields hashes, it's the type of relation that yaks doesn't know how to handle.

I just debugged yaks and got here:

```
[2, 11] in /Users/solnic/Workspace/rom-rb/rom/tmp/yaks/yaks/lib/yaks/pipeline.rb
    2:   class Pipeline
    3:     include Concord.new(:steps)
    4:
    5:     def call(input, env)
    6:       byebug
=>  7:       steps.inject(input) {|memo, (_, step)| step.call(memo, env) }
    8:     end
    9:
   10:     def insert_hooks(hooks)
   11:       new_steps = hooks.inject(steps) do |steps, (type, target_step, name, hook)|
(byebug) input
#<ROM::Relation::Loaded:0x007fc7245839a8 @source=#<Users dataset=#<ROM::Memory::Dataset data=[{:name=>"Jane"}]>>, @collection=[{:name=>"Jane"}]>
(byebug) input.to_ary
[{:name=>"Jane"}]
```

So, it seems like we indeed need a yaks mapper that would turn loaded relation into an array. OTOH given that yaks works OOTB with an array as a resource passed to `call` method, it *could* try to coerce the input by default, this would eliminate the need to setup additional yaks mappers for collection mapping.

WDYT?

**Comment by solnic** [comment]
@plexus oh and I'm definitely interested in a hacking session with you :)

**Comment by solnic** [comment]
I updated the title of this issue to better describe what we're trying to achieve here

**Comment by plexus** [comment]
Yaks can't assume that you're always mapping a collection/array. You could also be mapping a single object that happens to implement to_a/to_ary.

**Comment by plexus** [comment]
you can however configure this coercion very easily

```
Yaks.new do
  before :map do |object, env|
    object.to_ary
  end
end
```

**Comment by solnic** [comment]
OK I figured it out based on your examples, here's what works:

``` ruby
ROM.setup(:memory)

class Users < ROM::Relation[:memory]
  def by_name(name)
    restrict(name: name)
  end
end

rom = ROM.finalize.env

rom.relations.users << { name: 'Jane' }
rom.relations.users << { name: 'Joe' }

yaks = Yaks.new do
  default_format :hal
  rel_template 'http://api.example.com/rels/{rel}'
  format_options(:hal, plural_links: [:copyright])
  derive_mapper_from_object do |model|
    if model.respond_to?(:to_ary)
      CoercingCollectionMapper
    else
      super(model)
    end
  end
end

class BaseMapper < Yaks::Mapper
  def load_attribute(name)
    object[name]
  end
end

class CoercingCollectionMapper < Yaks::CollectionMapper
  def collection
    super.to_ary
  end
end

class HashMapper < BaseMapper
  link :self, '/api/users/{name}'
  attributes :name
end

users = rom.relation(:users).by_name('Jane')
puts JSON.load(yaks.call(users)).inspect
# => {"_embedded"=>{"http://api.example.com/rels/hashes"=>[{"name"=>"Jane", "_links"=>{"self"=>{"href"=>"/api/users/"}}}]}}
```

I couldn't make it work w/o those extra mappers. I guess it would be nice to have a builtin hash mapper. As I understand it now, it seems like we can derive model type from collection (loaded relation has a source object relation which has all the info needed to figure out what it is).

This is really cool Arne. I might add a thin integration layer for rom<=>yaks though as some things could be simplified so that people don't have to define those extra policy settings.

I'm gonna close this now as it's clear that what I wanted to do is possible. Thank you for your help :)
