### ISSUE TITLE
Start using Ataru

### ISSUE THREAD

**Issue by plexus** [plexus/yaks#55]
Some of the code examples in the README are getting out of date. There's a gem to test that stuff, we just need to start using it, and maybe adapt our docs to make sure they're testable.

**Comment by moonglum** [comment]
Nice :+1:

**Comment by plexus** [comment]
I've added Ataru and created a basic setup here https://github.com/plexus/yaks/commit/56dabc9fc47887813e4c56ba9e2236094685bec3

currently 8 out of 30 examples in the README fail, probably because they need some extra setup. A first step will be to get these to run, consequently we can start using some of the assertion capabilities that Ataru has.

**Comment by mifix** [comment]
see #61

**Comment by plexus** [comment]
Closed by #61, now also runs as part of the Travis build. Thanks @mifix !
