### ISSUE TITLE
Look for mappers in current namespace

### ISSUE THREAD

**Issue by plexus** [plexus/yaks#57]
When your models and mappers are in the same namespace, you still have to tell yaks to find the mappers in that namespace, otherwise it will try to find them at the top level. It would make more sense to look in the same namespace first.

``` ruby
class MyApp
  class Product < Sequel::Model
  end
  class ProductMapper < Yaks::Mapper
end

Yaks.new.call(Product.all)
# => Error: did you mean to implement ProductMapper
```

**Comment by groyoh** [comment]
@plexus This issue should be closed :wink:

**Comment by plexus** [comment]
do you need extra permissions to be able to close issues?

**Comment by groyoh** [comment]
To close issues I didn't create, I guess I do.

**Comment by plexus** [comment]
@groyoh @janko-m @chastell @fnordfish @danelowe @mpedrera 

I've made you all "collaborators" on this repository. This means you can merge pull requests, close issues, and push directly to the repo. (please don't push directly to the repo).

Now that more people are using and contributing to Yaks it makes sense to also have shared ownership. In practice not much will change. Changes should still be discussed, and we'll still go through pull requests and code review. I like in general for a pull request not to be merged by the person that created it. For any significant changes I plan to go through PRs as well from now on, and will wait until hopefully somebody else merges them :)

So the main difference in practice will be that you can now press "Merge" or "Close Issue".

**Comment by groyoh** [comment]
:+1: would it be possible to more rights on Travis CI? The thing is that since rbx has been failing quite some times, to make it pass we have the following possibilities:
* close/open the pull request
* amend and force push

Both of them restart the whole travis pipeline which may take some times.
On my own travis repo, I can click on the "restart task" button to just restart the only task that is failing, and I would love to be able to do that with PR too. 

You can see on the top-right corner the button I'm talking about:
![image](https://cloud.githubusercontent.com/assets/7434196/7613175/70c20616-f98f-11e4-8cf7-c771c01976cc.png)

**Comment by plexus** [comment]
I don't see anything I can configure regarding permissions on Travis. I guess it will just take the commit bit from Github, but maybe it needs some time to sync.

**Comment by groyoh** [comment]
Ok, I'll wait and see then!

**Comment by chastell** [comment]
> I've made you all "collaborators" on this repository.

Thanks! Much appreciated. \o/

> I guess it will just take the commit bit from Github, but maybe it needs some time to sync.

I think the commit bit is enough – make sure you’re logged into Travis, though (guess how I learned that one…).

**Comment by groyoh** [comment]
@plexus @chastell you were right! :smile:

**Comment by danelowe** [comment]
Thanks @plexus Yaks is such a great project, not only because it is so useful but also its fun to be involved with and the way it is set up and managed makes sure we are all learning something new each time we contribute. :heart:

**Comment by groyoh** [comment]
> the way it is set up and managed makes sure we are all learning something new each time we contribute
@danelowe :+1:
