### ISSUE TITLE
When using `derive_mapper_from_object`, Arrays are no longer matched

### ISSUE THREAD

**Issue by moonglum** [plexus/yaks#72]
When I give my own `derive_mapper_from_object`, the mapping of Arrays no longer works. I'm currently writing an app that wraps a very, very ugly XML-RPC API into a nice and provides shiny Hypermedia API. The type of object is in every hash that I get back from the API in an attribute called 'resource_type'. I don't see any reason why I would first convert it to a class, so I'm using Yaks' nice pipeline architecture to convert the Arrays of Hashes I get from the other API to HAL Responses using Yaks. However, when providing my own deriviation algorithms, the default of mapping an array does not work any longer. Here is the snippet from my code base:

```ruby
derive_mapper_from_object do |model|
  Kernel.const_get("#{model.fetch('resource_type').capitalize}Mapper")
end
```

What can I do to say "please do what you always did when you get an array"?

**Comment by moonglum** [comment]
Is this the solution?

```ruby
  derive_mapper_from_object do |model|
    return Yaks::CollectionMapper if model.respond_to? :to_ary
    Kernel.const_get("#{model['resource_type'].capitalize}Mapper")
  end
```

If so, I would provide a PR to describe it in the README.

**Comment by groyoh** [comment]
IMO this is pretty straightforward. If you provide your own derivation algorithm, it seems logical that you also provide derivation for collections.

**Comment by plexus** [comment]
Hi @moonglum! Yes, that snippet seems correct at first glance. I agree it wouldn't hurt to document that, or expound a bit more on the distinction of singular and collection resources.

We could also split the logic up in the policy class, have a `derive_mapper_from_object` that delegates to `derive_mapper_from_collection` and `derive_mapper_from_model`, so you could override just one of these. 

Can't think of a better word for `_model` off the top of my hat. `_instance` maybe? `_atom`? `_singular`?

Actually in the code we tend to use `item` to mean something that's part of a collection, so maybe `derive_mapper_from_item` would work?

**Comment by moonglum** [comment]
Great! Yep, I'm all for splitting it into two parts. And I really like the `item` variant as it seems consistent with the wording!

**Comment by groyoh** [comment]
@moonglum I'm closing this issue since #92 implement the wanted features.
