### ISSUE TITLE
Broken master build 

### ISSUE THREAD

**Issue by plexus** [plexus/yaks#73]
Current setup fails on Travis for rbx-rspec-yaks:html, which is odd because I don't recall yaks-html really having tests, but might be a load time issue in rubinius.

**Comment by groyoh** [comment]
I tried to reproduce it locally but I did not manage to do so. Travis failed one more time with rbx during one of the build of #67.

**Comment by plexus** [comment]
I added rbx to the allowed failures. There is really no reason for us to sink more time into it. Yaks is pure Ruby and not all that exotic, keeping compatibility with MRI and JRuby means we *should* stay compatible with rbx as well. If anybody steps up who uses Rubinius and finds issues I'll be happy to work with them to get them resolved.
