### ISSUE TITLE
Release 0.10.0

### ISSUE THREAD

**Issue by plexus** [plexus/yaks#90]
I think we've built up enough improvements to do another release. Main things to still go in will be #86 and #88.

If you have apps that use Yaks now's the time to run them against master and report any problems. I already ran our API tests and all seems fine.

**Comment by groyoh** [comment]
I'm currently working on a PR for `mapper_for` and `derive_mapper_from_single_object/collection` as defined in #76 and #72. So maybe we could wait until that is done :smile:
`mapper_for` is not ready yet, but I could create a PR for the other two.

**Comment by plexus** [comment]
Or we can release 0.11.0 as soon as these are in :) The rate of releases has been slowing down, and we have plenty of new goodness for the world to see.

In general you're always welcome to make a PR, even if things or not 100% finished yet. It's a good way to get feedback.

**Comment by groyoh** [comment]
We could also do that :wink: I'll open a PR then!

**Comment by plexus** [comment]
0.10.0 has been released :tada: 

![baby-excited](https://cloud.githubusercontent.com/assets/32212/7700449/1111e3f0-fe1f-11e4-92ce-5be08612ee39.gif)

The previous release was two months ago, and a lot has happened since, so it really was about time.

If the current pace of development keeps up I'd like to release every four to six weeks.

Thanks a lot @groyoh @janko-m @danelowe @chastell @mifix ! It's really great to have you around.

**Comment by danelowe** [comment]
Best gif yet!
